### ISSUE TITLE
واژگان انگلیسی در میان متن فارسی

### ISSUE THREAD

**Issue by 5j9** [m-o-s-t-a-f-a/lilak#13]
<div dir=rtl>
خیلی از متون فارسی، به‌ویژه متون علمی، دارای واژگان انگلیسی در میان خودشان هستند. آیا راهی هست که کل این موارد (مثلاً همه کلماتی که با الفبای لاتین هستند) در متن فارسی نادیده گرفته شوند (روش دیگری که به ذهنم می‌رسد ساختن یک دیکشنری چندزبانه است که فکر می‌کنم حجم زیادی بگیرد و شاید شدنی نباشد)

**Comment by m-o-s-t-a-f-a** [comment]
مرورگر فایرفاکس این مشکل را دارد.
اما در مرورگر کروم این امکان هست.
من با کمک دو پیکره 
VOA
و همشهری توانستم فهرستی از کلمات انگلیسی پرکاربرد در زبان فارسی پیدا کنم:
https://github.com/m-o-s-t-a-f-a/lilak/blob/master/src/dic_delta

اگر کمی صبر کنیم قرار است این پروژه به کروم افزوده شود.
