### ISSUE TITLE
نقش‌نمای اضافه پس از صفت‌های منتهی به الف

### ISSUE THREAD

**Issue by 5j9** [m-o-s-t-a-f-a/lilak#14]
<div dir=rtl>
موارد زیر که بیشتر حاصل ترکیب [صفت‌های منتهی به الف](http://danasrs.com/lexicon/search.php?text=%25%D8%A7&ana_text=&ana_type=84&pronounce=&lemma=&min_freq=&max_freq=&user_id=-1&export_type=) با یک اسم/صفت هستند اشتباه شناسایی می‌شوند:
- بلندای آسمان
- آرمانگرای حقیقی
- اصولگرای واقعی
- اسلامگرای نمونه
- بامعنای ژرف‌معنی
- [روستایِ] باصفای فلان
- اقتدارگرای جاه‌طلب
- [پیشنهادِ] کارگشای جناب‌عالی

البته مطمئن نیستم از نظر دستور زبان چگونه طبقه‌بندی می‌شوند، ولی فکر می‌کنم غالب مواردی که در پیوند بالا آمده‌اند چنین مشکلی دارند.

**Comment by m-o-s-t-a-f-a** [comment]
این مشکل حل شد. یکی از پسوندها جا مانده بود!
https://github.com/m-o-s-t-a-f-a/lilak/commit/52f67e8cf65d4a365b9983b8fe905d638cbcf880
