### ISSUE TITLE
شناسایی‌نشدن یای نکره در انتهای جمع‌های «ان»

### ISSUE THREAD

**Issue by 5j9** [m-o-s-t-a-f-a/lilak#16]
<div dir=rtl>
برای مثال «یکتاپرستان» درست شناسایی می‌شود ولی «یکتاپرستانی» نه. به طور مشابه برای موارد زیر:
- درختانی
- ایزدانی 
- آموزگارانی

به نظر می‌رسد این موضوع  مرتبط با #7 است. (واژه‌هایی که حالت جمعشان مستقیم در دادگان وارد نشده این مشکل را دارند و اگر به انتهای مثال‌های آنجا یک «ی» اضافه کنیم همین مشکل ظاهر می‌شود)

**Comment by m-o-s-t-a-f-a** [comment]
پسوند «انی» اضافه شد. با تشکر
