### ISSUE TITLE
صفت مفعولی + همزه

### ISSUE THREAD

**Issue by 5j9** [m-o-s-t-a-f-a/lilak#21]
<div dir=rtl>
اگر بعد از صفت‌های مفعولی [که از ترکیب بن ماضی + ه تشکیل می‌شوند] همزهٔ روی «ـه» بیاید در اکثر موارد به عنوان اشتباه شناسایی می‌شوند، در حالی که درست هستند. مثال:
«حملات گستردهٔ تروریستی»
«دودمان برافتادهٔ قاجار»
«عملیات پیچیدهٔ ریاضی»
«شیر دوشیدهٔ تازه»
«تنهٔ پوسیدهٔ درخت»
و ...

**Comment by m-o-s-t-a-f-a** [comment]
اصلاح شد. 
با تشکر
