### ISSUE TITLE
کلمات غیر رسمی

### ISSUE THREAD

**Issue by reza1615** [m-o-s-t-a-f-a/lilak#24]
الان خروجی این پروژه کلمات غیررسمی‌ای مانند
اونا
بریم
آروم
بشیم
داغون
میده
میون
به نظرم برای هانسپل باید حد و مرز مشخص کرد آیا فقط برای موارد رسمی و کتابی ست یا برای موارد محاوره‌ای هم کاربرد دارد
اگر قرار باشد غیر رسمی‌ها را هم پشتیبانی کند پس عبارت‌های زیر هم باید به آن اضافه شود مانند
تهرون
ایرون الان ایرونی را می‌شناسد!
ایشون

**Comment by reza1615** [comment]
اگر قرار باشد غیر رسمی‌ها را هم پشتیبانی کند پس عبارت‌های زیر هم باید به آن اضافه شود مانند
تهرون
ایرون
ایشون

**Comment by m-o-s-t-a-f-a** [comment]
رضا جان. فکر کنم بهتر است با دوستان در ویکی‌پدیای فارسی در این مورد بحث کنید. آیا لازم است در نوشتار از واژگان گفتاری هم ایراد گرفت؟ من دستکم خودم کتاب «سنگ صبور» صادق چوبک را می‌توانم مثال بزنم که پر است از کلمات محاوره‌ای روزمره.

**Comment by reza1615** [comment]
در 
https://en.wiktionary.org/wiki/Category:English_contractions
کلمات غیررسمی انگلیسی فهرست شده‌است اگر کلمات را در یک جعبهٔ متنی قرار دهید متوجه می‌شود اکثرشان غلط محسوب می‌شوند به خصوص آنهایی که ' ندارند چون ' را هانسپل درنظر نمی‌گیرد در نتیجه بخش دوم کلمهٔ جداگانه به حساب می‌آید مثلا
hafta
spose
witcha
whaddya
wilbe
leggo
همگی غلط محسوب می‌شوند با وجودی که در سایت 
http://www.urbandictionary.com/
همگی معنی دارند و غیررسمی هستند از سویی بودن کلمات عامیانه باعث می‌شود متن‌های رسمی هم با مشکل مواجه شوند و نتوان به درست بودن آنها اطمینان داشت به عنوان مثال
ملیون به جای میلیون اگر در یک متن رسمی باشد غلط املایی ست.

**Comment by reza1615** [comment]
در
https://fa.wikipedia.org/wiki/%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7:%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87%E2%80%8C%DB%8C%D8%A7%D8%A8/%D9%81%D9%87%D8%B1%D8%B3%D8%AA/%D8%BA%DB%8C%D8%B1%D8%B1%D8%B3%D9%85%DB%8C
فهرستی از کلمات غیر رسمی + صرف فعل به صورت غیر رسمی آمده که می‌توانید این موارد را از دادگان کم کنید یا برچسب مجزا بزنید.
برچسب‌ها بر پایه زبان‌شناسی باید به شرح زیر باشد
slang:
زبان عامیانه معمولاً به زبان کوچه‌بازاری (و بعضاً زبانِ فرودست) می‌گویند و همیشه «نشان‌دار» است؛ مثال: دیفال، جعده، شمبه، چاکرتیم، چمنتیم، کرتیم، واس‌ماس، خِـلی سالاری!
broken language:
زبان شکسته: کاملاً فراگیر و غیرنشان‌دار است، یعنی عملاً همه آن را به‌کار می‌برند، حتی شاه، ملکه، رهبر، و سایر مقامات و همهٔ قشرها؛ چند مثال: می‌رم، نمی‌شه، بگم، نگم، میون، همه‌شون/ همشون (بیش از بیست‌هزار مثال از این دست در فارسی داریم)
مواردی که در بالا ذکر شد بیشتر به زبان شکسته می‌خورند تا زبان عامیانه. البته برای برچسب‌گذاری می‌توان این دو را جزو زبان غیررسمی آورد تا کار راحت‌تر باشد.

**Comment by m-o-s-t-a-f-a** [comment]
این مورد را بیشتر باز نمی‌گذارم. می توانیم دیکشنری دیگری برای کلمات غیر رسمی ایجاد کنیم.
