### ISSUE TITLE
بعضی صورت‌های جمع با «ان»‏ را به عنوان اشتباه شناسایی می‌کند

### ISSUE THREAD

**Issue by 5j9** [m-o-s-t-a-f-a/lilak#7]
بعضی از صورت‌های جمع را به عنوان اشتباه نشانه‌گذاری می‌کند:

خردمند --> خردمندان
شکارچی --> شکارچیان 
روزگار --> زورگاران
حوری --> حوریان

**Comment by m-o-s-t-a-f-a** [comment]
در مورد علامت جمع «ان» در زبان فارسی مشکل که پیش می‌آید این است که برخلاف علامت جمع «ها» این علامت جمع به همه اسامی نمی‌چسبد. تنها اسامی جانداران و برخی استثناهای دیگر شامل این قاعده هستند.

در حال حاضر مشکل بالا حل شده است. اما شاید بهتر باشد بین اسامی جاندار و بیجان تفکیک قایل شویم.
