### ISSUE TITLE
ـهٔ

### ISSUE THREAD

**Issue by 5j9** [m-o-s-t-a-f-a/lilak#8]
مضاف‌های مختوم به های غیرملفوظ از نویسهٔ «ٔ» به جای کسره استفاده می‌کنند. به نظر می‌رسد در همهٔ موارد این‌ها به عنوان اشتباه شناسایی می‌شوند. مثال:

خانهٔ سبز
دروازهٔ فوتبال
پروانهٔ ساخت
شهریهٔ دانشگاه
نامهٔ او

(از افزونهٔ فایرفاکس استفاده می‌کنم)

**Comment by m-o-s-t-a-f-a** [comment]
این ایراد در نسخه بعدی رفع خواهد شد. 
با تشکر.

**Comment by m-o-s-t-a-f-a** [comment]
It is fixed. please check the latest version.
